import Head from "next/head";
import Hero from "../src/components/styled/Hero";
import Heading from "../src/components/styled/Heading";

export default function About() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero>
        <Heading>About</Heading>
      </Hero>
    </>
  );
}
