import Head from "next/head";
import Heading from "../src/components/styled/Heading";
import Grid from "../src/components/home/Grid/Grid";
import {
  useERC20Balances,
  useMoralis,
  useMoralisWeb3Api,
  useNativeBalance,
  useTokenPrice,
} from "react-moralis";
import {
  StyledLink,
  PrimaryButton,
  AddressButton,
  AvaxLogo,
  AvalancheButton,
} from "../src/components/commons/lib";
import { useEffect } from "react";

export default function Contact() {
  const {
    getBalances,
    data: balance,
    nativeToken,
    error,
    isLoading,
  } = useNativeBalance({ chain: "avalanche" });

  const { authenticate, logout, isAuthenticated, account } = useMoralis();
  const dataToken = useTokenPrice({
    address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7",
    chain: "avalanche",
  });
  const Web3Api = useMoralisWeb3Api();

  const data = useERC20Balances();
  const handleLogin = () => {
    authenticate();
  };
  console.log(account);
  console.log("dataToken", dataToken);

  const handleLogout = () => {
    logout();
  };
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ minHeight: "calc(100vh - 140px)" }}>
        {isAuthenticated ? (
          <button onClick={handleLogout}>Logout</button>
        ) : (
          <button onClick={handleLogin}>Login</button>
        )}
        <Grid />

        <StyledLink>Hello</StyledLink>
        {/* <PrimaryButton>Connect to a wallet</PrimaryButton> */}

        <AvalancheButton>Avalanche</AvalancheButton>
        {isAuthenticated ? (
          <AddressButton>
            <AvaxLogo src="/avalanche-avax-logo.png" />
            <span>{account}</span>
          </AddressButton>
        ) : (
          <PrimaryButton onClick={handleLogin}>
            Connect to a wallet
          </PrimaryButton>
        )}
      </div>
    </>
  );
}
