import Head from "next/head";
import Hero from "../components/styled/Hero";
import Heading from "../components/styled/Heading";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>Contact</Heading>
      </Hero>
    </>
  );
}
