import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../src/components/styled/Hero";
import Heading from "../src/components/styled/Heading";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero>
        <Heading>HOME</Heading>
      </Hero>
    </>
  );
};

export default Home;
