import type { NextPage } from "next";
import Head from "next/head";
// import Hero from "../src/components/styled/Hero";
// import Heading from "../src/components/styled/Heading";
import Cards from "../src/components/home/Cards/Cards";
import {
  useERC20Balances,
  useMoralis,
  useMoralisWeb3Api,
  useNativeBalance,
  useTokenPrice,
} from "react-moralis";
import Table from "../src/components/home/Table/Table";

const Home: NextPage = () => {
  const { authenticate, logout, isAuthenticated, account } = useMoralis();
  const handleLogout = () => {
    logout();
  };
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cards />
      <Table />

      {/* <Heading>HOME</Heading>
      <PriceTag>$1000</PriceTag> */}
      {isAuthenticated ? (
        <button onClick={handleLogout}>Logout</button>
      ) : (
        <span>You have to Log in</span>
      )}
    </>
  );
};

export default Home;
