import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { useMoralis } from "react-moralis";
import PoolCards from "../src/components/home/Cards/PoolCards";
import TokenCards from "../src/components/home/Cards/TokenCards";
import TableTabs from "../src/components/home/Table/TableTabs";

const Home: NextPage = () => {
  const [activeTab, setActiveTab] = React.useState<
    "pool" | "tokens" | "lending"
  >("pool");

  const handleTabChange = (tab: "pool" | "tokens" | "lending") => {
    setActiveTab(tab);
  };
  const { logout } = useMoralis();

  const handleLogout = () => {
    logout();
  };

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {activeTab === "tokens" && <TokenCards />}
      {activeTab === "pool" && <PoolCards />}
      <TableTabs handleTabChange={handleTabChange} activeTab={activeTab} />
    </>
  );
};

export default Home;
